// ─── Export Session Tool ───
// Export session data to ./clarik-exports/ — NEVER ~/Downloads
// Supports json and markdown formats.

import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { ToolResult, Decision, FileMapping } from '../types.js';
import {
  getExportDir,
  getProjectDir,
  readJson,
  fileExists,
  generateId,
} from '../storage.js';
import type { DecisionTimeline } from '../types.js';
import type { FileMapStore } from '../types.js';

interface ExportData {
  exportedAt: string;
  projectId: string;
  decisions: Decision[];
  fileMappings: FileMapping[];
}

/**
 * Export session/project data to ./clarik-exports/
 * NEVER exports to ~/Downloads — always project-local.
 *
 * @param projectId - The project identifier
 * @param format - Export format: 'json' or 'markdown'
 */
export async function exportSession(
  projectId: string,
  format: string
): Promise<ToolResult> {
  try {
    const normalizedFormat = format.toLowerCase().trim();
    if (normalizedFormat !== 'json' && normalizedFormat !== 'markdown') {
      return {
        content: [{ type: 'text', text: `Unsupported format '${format}'. Use 'json' or 'markdown'.` }],
        isError: true,
      };
    }

    // Gather project data
    const projectDir = getProjectDir(projectId);
    const projectDirExists = await fileExists(projectDir);

    if (!projectDirExists) {
      return {
        content: [{ type: 'text', text: `No data found for project '${projectId}'.` }],
        isError: true,
      };
    }

    // Read decisions
    const decisionsPath = path.join(projectDir, 'decisions.json');
    const decisionStore = await readJson<DecisionTimeline>(decisionsPath, {
      version: 1,
      projectId,
      decisions: [],
    });

    // Read file map
    const fileMapPath = path.join(projectDir, 'file_map.json');
    const fileMapStore = await readJson<FileMapStore>(fileMapPath, {
      version: 1,
      projectId,
      mappings: [],
    });

    const exportData: ExportData = {
      exportedAt: new Date().toISOString(),
      projectId,
      decisions: decisionStore.decisions,
      fileMappings: fileMapStore.mappings,
    };

    // Ensure export directory exists — ALWAYS ./clarik-exports/
    const exportDir = getExportDir();
    await fs.mkdir(exportDir, { recursive: true });

    const exportId = generateId('export');
    let exportPath: string;
    let exportContent: string;

    if (normalizedFormat === 'json') {
      exportPath = path.join(exportDir, `${exportId}.json`);
      exportContent = JSON.stringify(exportData, null, 2);
    } else {
      // Markdown format
      exportPath = path.join(exportDir, `${exportId}.md`);
      exportContent = buildMarkdownExport(exportData);
    }

    await fs.writeFile(exportPath, exportContent, 'utf-8');

    return {
      content: [{
        type: 'text',
        text: `Session exported successfully!\n\n- **Format:** ${normalizedFormat}\n- **Path:** ${exportPath}\n- **Decisions:** ${exportData.decisions.length}\n- **File mappings:** ${exportData.fileMappings.length}`,
      }],
    };
  } catch (error) {
    console.error('[clarik] Error exporting session:', error);
    return {
      content: [{ type: 'text', text: `Export error: ${error}` }],
      isError: true,
    };
  }
}

/** Build a human-readable markdown export */
function buildMarkdownExport(data: ExportData): string {
  const lines: string[] = [
    `# Clarik Session Export`,
    ``,
    `**Project:** ${data.projectId}`,
    `**Exported:** ${data.exportedAt}`,
    ``,
  ];

  // Decisions section
  lines.push(`## Decisions (${data.decisions.length})`);
  lines.push(``);

  if (data.decisions.length === 0) {
    lines.push(`No decisions recorded.`);
  } else {
    for (const dec of data.decisions) {
      lines.push(`### ${dec.decision}`);
      lines.push(``);
      lines.push(`- **ID:** ${dec.id}`);
      lines.push(`- **Date:** ${dec.date}`);
      lines.push(`- **Reason:** ${dec.reason}`);
      if (dec.affectedFiles.length > 0) {
        lines.push(`- **Affected files:**`);
        for (const file of dec.affectedFiles) {
          lines.push(`  - ${file}`);
        }
      }
      if (dec.supersedes) {
        lines.push(`- **Supersedes:** ${dec.supersedes}`);
      }
      lines.push(``);
    }
  }

  // File Map section
  lines.push(`## File Map (${data.fileMappings.length})`);
  lines.push(``);

  if (data.fileMappings.length === 0) {
    lines.push(`No file mappings recorded.`);
  } else {
    lines.push(`| File | Purpose | Last Updated |`);
    lines.push(`|------|---------|--------------|`);
    for (const fm of data.fileMappings) {
      lines.push(`| ${fm.filePath} | ${fm.purpose} | ${fm.lastUpdated} |`);
    }
  }

  lines.push(``);
  lines.push(`---`);
  lines.push(`*Generated by Clarik MCP Server*`);

  return lines.join('\n');
}
